import { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  CircularProgress,
  Alert,
  Paper,
  Divider
} from '@mui/material';
import { fetchEmployeePerformance } from '../api/employees';
import type { EmployeePerformance } from '../api/employees';
import KPICard from '../components/KPICard';
import RolePerformanceChart from '../components/RolePerformanceChart';
import MonthlyPerformanceChart from '../components/MonthlyPerformanceChart';
import EmployeeTable from '../components/EmployeeTable';
import SalesLeaderboard from '../components/SalesLeaderboard';
import PeopleIcon from '@mui/icons-material/People';
import PersonIcon from '@mui/icons-material/Person';
import AttachMoneyIcon from '@mui/icons-material/AttachMoney';
import PercentIcon from '@mui/icons-material/Percent';
import EmojiEventsIcon from '@mui/icons-material/EmojiEvents';

export default function EmployeeDashboard() {
  const [data, setData] = useState<EmployeePerformance | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        const result = await fetchEmployeePerformance();
        setData(result);
        setError(null);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load data');
      } finally {
        setLoading(false);
      }
    }

    loadData();
  }, []);

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Box p={3}>
        <Alert severity="error">{error}</Alert>
      </Box>
    );
  }

  if (!data) {
    return (
      <Box p={3}>
        <Alert severity="info">No data available</Alert>
      </Box>
    );
  }

  const activePercentage = data.total_employees > 0
    ? ((data.active_employees / data.total_employees) * 100).toFixed(1)
    : '0';

  // Transform top performers to leaderboard format
  const leaderboardData = data.top_performers.map(emp => ({
    employee_id: emp.employee_id,
    name: emp.employee_name,
    role: emp.role,
    total_sales: emp.total_sales,
    total_revenue: emp.total_revenue,
    commission_earned: emp.commission_earned,
    average_sale_price: emp.average_deal_size
  }));

  return (
    <Box sx={{ p: 3 }}>
      <Typography variant="h4" gutterBottom fontWeight="bold" color="primary">
        Employee Performance Dashboard
      </Typography>
      <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
        Comprehensive employee metrics and performance tracking
      </Typography>

      {/* KPI Cards */}
      <Box
        sx={{
          display: 'flex',
          flexWrap: 'wrap',
          gap: 2,
          mb: 4
        }}
      >
        <Box sx={{ flex: '1 1 200px', minWidth: '200px' }}>
          <KPICard
            title="Total Employees"
            value={data.total_employees.toString()}
            icon={<PeopleIcon />}
            color="#2196f3"
          />
        </Box>
        <Box sx={{ flex: '1 1 200px', minWidth: '200px' }}>
          <KPICard
            title="Active Employees"
            value={`${data.active_employees} (${activePercentage}%)`}
            icon={<PersonIcon />}
            color="#4caf50"
          />
        </Box>
        <Box sx={{ flex: '1 1 200px', minWidth: '200px' }}>
          <KPICard
            title="Total Commission Paid"
            value={formatCurrency(data.total_commission_paid)}
            icon={<AttachMoneyIcon />}
            color="#ff9800"
          />
        </Box>
        <Box sx={{ flex: '1 1 200px', minWidth: '200px' }}>
          <KPICard
            title="Avg Commission Rate"
            value={`${data.average_commission_rate.toFixed(2)}%`}
            icon={<PercentIcon />}
            color="#9c27b0"
          />
        </Box>
      </Box>

      {/* Monthly Performance Trend */}
      <Paper elevation={2} sx={{ p: 2, mb: 4 }}>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          Monthly Revenue Performance
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Historical revenue generated by sales team
        </Typography>
        <Divider sx={{ mb: 2 }} />
        <MonthlyPerformanceChart data={data.monthly_performance} />
      </Paper>

      {/* Charts and Leaderboard Section */}
      <Box
        sx={{
          display: 'flex',
          flexWrap: 'wrap',
          gap: 3,
          mb: 4
        }}
      >
        {/* Performance by Role */}
        <Paper
          elevation={2}
          sx={{ flex: '1 1 500px', minWidth: '300px', p: 2 }}
        >
          <Typography variant="h6" gutterBottom fontWeight="bold">
            Performance by Role
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Total revenue generated by employee role
          </Typography>
          <Divider sx={{ mb: 2 }} />
          <RolePerformanceChart data={data.performance_by_role} />
        </Paper>

        {/* Top Performers Leaderboard */}
        <Paper
          elevation={2}
          sx={{ flex: '1 1 400px', minWidth: '300px', p: 2 }}
        >
          <Typography variant="h6" gutterBottom fontWeight="bold">
            <EmojiEventsIcon sx={{ verticalAlign: 'middle', mr: 1, color: '#ffd700' }} />
            Top Performers
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Highest revenue-generating employees
          </Typography>
          <Divider sx={{ mb: 2 }} />
          <SalesLeaderboard performers={leaderboardData} />
        </Paper>
      </Box>

      {/* Role Performance Details */}
      {data.performance_by_role.length > 0 && (
        <Paper elevation={2} sx={{ p: 3, mb: 4 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            Role Performance Breakdown
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Detailed metrics by employee role
          </Typography>
          <Divider sx={{ mb: 2 }} />
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', justifyContent: 'center' }}>
            {data.performance_by_role.map((role) => (
              <Box
                key={role.role}
                sx={{
                  p: 2,
                  border: '1px solid #e0e0e0',
                  borderRadius: 2,
                  minWidth: 220,
                  textAlign: 'center'
                }}
              >
                <Typography variant="body2" fontWeight="bold" color="primary">
                  {role.role}
                </Typography>
                <Typography variant="h5" fontWeight="bold" sx={{ my: 1 }}>
                  {formatCurrency(role.total_revenue)}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {role.employee_count} employees • {role.total_sales} sales
                </Typography>
                <Divider sx={{ my: 1 }} />
                <Typography variant="caption" color="text.secondary">
                  Avg per employee: {formatCurrency(role.average_revenue_per_employee)}
                </Typography>
              </Box>
            ))}
          </Box>
        </Paper>
      )}

      {/* Commission Details for Top Performers */}
      {data.top_performers.length > 0 && (
        <Paper elevation={2} sx={{ p: 3, mb: 4 }}>
          <Typography variant="h6" gutterBottom fontWeight="bold">
            Top Performer Commission Details
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Commission breakdown for top revenue generators
          </Typography>
          <Divider sx={{ mb: 2 }} />
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            {data.top_performers.slice(0, 5).map((employee) => (
              <Box
                key={employee.employee_id}
                sx={{
                  p: 2,
                  border: '1px solid #e0e0e0',
                  borderRadius: 2,
                  flex: '1 1 180px',
                  minWidth: 180
                }}
              >
                <Typography variant="body2" fontWeight="bold" noWrap>
                  {employee.employee_name}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {employee.role}
                </Typography>
                <Typography variant="h6" fontWeight="bold" color="success.main" sx={{ mt: 1 }}>
                  {formatCurrency(employee.commission_earned)}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  Commission @ {employee.commission_rate}%
                </Typography>
                <Divider sx={{ my: 1 }} />
                <Typography variant="caption" color="text.secondary">
                  {employee.total_sales} sales • Avg: {formatCurrency(employee.average_deal_size)}
                </Typography>
              </Box>
            ))}
          </Box>
        </Paper>
      )}

      {/* All Employees Table */}
      <Paper elevation={2} sx={{ p: 2 }}>
        <Typography variant="h6" gutterBottom fontWeight="bold">
          All Employees
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Complete employee roster with performance metrics
        </Typography>
        <Divider sx={{ mb: 2 }} />
        <EmployeeTable employees={data.employee_list} />
      </Paper>
    </Box>
  );
}
